version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
      - QDRANT_URL=http://qdrant:6333

  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    ports:
      - "6333:6333"